### ISSUE TITLE
AttributeError: module 're' has no attribute 'Pattern'

### ISSUE THREAD

**Issue by wavebeem** [minamorl/trishula#1]
I tried making this script and it's crashing:

```py
import trishula as T

print(dir(T))
print()

grammar = (
    T.Value("[") >>
    T.Regexp(r"[0-9\.]+") >>
    # T.Regexp(r"[0-9\.]+") @ float >>
    # (T.Value("3.14") @ (lambda x: float(x.value))) >>
    T.Value("]")
) @ (lambda xs: xs[1])

result = T.Parser().parse(grammar, "[3.14]")
print(vars(result))
```

```
% python --version
Python 3.6.5
```

**Comment by minamorl** [comment]
Hi @wavebeem .

```python
import trishula as T

print(dir(T))
print()

grammar = (
    T.Value("[") >>
    T.Regexp(r"[0-9\.]+") >>
    # T.Regexp(r"[0-9\.]+") @ float >>
    # (T.Value("3.14") @ (lambda x: float(x.value))) >>
    T.Value("]")
) @ (lambda xs: T.Node(xs.status, xs.index, xs.value[1])) # I changed this line

result = T.Parser().parse(grammar, "[3.14]")
print(vars(result))
```
This works in 3.7.0 . Please try it.

**Comment by wavebeem** [comment]
Oh I see, `@` is actually flatMap, not map! It would be nice to have a simple `map` operator that just takes value 😄

**Comment by minamorl** [comment]
I reproduced same problem in 3.6.5. Hmm...

**Comment by wavebeem** [comment]
I'm installing Python 3.7.2 right now so I can try your example

**Comment by wavebeem** [comment]
OK it works in 3.7.2! So my suggestion is use "@" for map and find a different operator for flatMap. I think map is more common so you should add that version :)

**Comment by minamorl** [comment]
Thanks for quick reply :)
That's nice idea to change "@" operator for `map`. I will fix it.

BTW I removed the map from your code:
```python
import trishula as T

print(dir(T))
print()

grammar = (
    T.Value("[") >>
    T.Regexp(r"[0-9\.]+") >>
    # T.Regexp(r"[0-9\.]+") @ float >>
    # (T.Value("3.14") @ (lambda x: float(x.value))) >>
    T.Value("]")
)

result = T.Parser().parse(grammar, "[3.14]")
print(vars(result))
```

The result is:
```python
{'status': <Status.SUCCEED: 1>, 'index': 6, 'value': [['[', '3.14'], ']']}
```

The value becomes `[[ '[' , '3.14' ], ']']` so `xs.value[1]` is `]`.
Maybe this is not what you expected because of current implementation. Do you think it is okay?

**Comment by wavebeem** [comment]
Yeah I just realized that `>>` always makes a new list...

What if `>>` was Parsimmon `.then` and `<<` was Parsimmon `.skip`?

```py
grammar = (
  T.Value("[") >>
  (T.Regexp(r"[0-9]+") @ float) <<
  T.Value("]")
)
```

**Comment by minamorl** [comment]
Cool. I will introduce it.

Sorry, could you describe the actual difference between `map` and `flatMap`? To my understanding, passed function that takes pure value is `map` and the function that takes `Node` object (current implementation of `@`) is `flatMap`. Is that correct?

**Comment by wavebeem** [comment]
Technically I guess this is not map vs flatMap but it's similar... One returns T.Node and the other returns just a value.

I think two functions like this:

```py
T.Regex(r"[0-9]+").map(float)
# --- or ---
T.Regex(r"[0-9]+").map(lambda value: float(value))
```

vs

```py
T.Regex(r"[0-9]+").other_map(lambda node:
  T.Node(node.status, node.index, float(node.value))
)
```

**Comment by minamorl** [comment]
Okay. Now I understand it completely. 👍
